# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "mpt3sas" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/c92e4a99-1f39-4d9b-b22b-03e656189ba5";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/c92e4a99-1f39-4d9b-b22b-03e656189ba5";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" ];
    };

  fileSystems."/var" =
    {
      device = "/dev/disk/by-uuid/c92e4a99-1f39-4d9b-b22b-03e656189ba5";
      fsType = "btrfs";
      options = [ "subvol=@var" "compress=zstd" "noatime" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/c92e4a99-1f39-4d9b-b22b-03e656189ba5";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/tmp" =
    {
      device = "/dev/disk/by-uuid/c92e4a99-1f39-4d9b-b22b-03e656189ba5";
      fsType = "btrfs";
      options = [ "subvol=@tmp" "compress=zstd" "noatime" ];
    };

  fileSystems."/srv" =
    {
      device = "/dev/disk/by-uuid/c92e4a99-1f39-4d9b-b22b-03e656189ba5";
      fsType = "btrfs";
      options = [ "subvol=@srv" "compress=zstd" "noatime" ];
    };

  fileSystems."/opt" =
    {
      device = "/dev/disk/by-uuid/c92e4a99-1f39-4d9b-b22b-03e656189ba5";
      fsType = "btrfs";
      options = [ "subvol=@opt" "compress=zstd" "noatime" ];
    };

  fileSystems."/root" =
    {
      device = "/dev/disk/by-uuid/c92e4a99-1f39-4d9b-b22b-03e656189ba5";
      fsType = "btrfs";
      options = [ "subvol=@root" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/1E3A-FFB0";
      fsType = "vfat";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/d0bfc567-2706-4754-a5c4-f6a1b69039f3"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
